sudo: required
services:
    - docker

before_install:
    - docker build -t camenburg/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true camenburg/docker-react npm run test -- --coverage

language:
    generic
