sudo: required
services:
    - docker

before_install:
    - docker build -t camenburg/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true camenburg/docker-react npm run test -- --coverage

language:
    generic

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-156488043559"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    


        